version: '3'

volumes:
   monorail-static-files:

networks:
    zbmcnet:
        driver: bridge
        ipam:
          config:
           - subnet: 172.32.128.0/20
    zonctrol:   # note: networks get assigned to interface based on sorted name. put this PAST 'default'
        driver: bridge
        ipam:
          config:
            - subnet: 172.31.128.0/20

services:
  mongo:
    image: mongo:latest

  rabbitmq:
    image: rabbitmq:management

  files:
    image: rackhd/files:${RACKHD_TAG:-latest}
    volumes:
      - monorail-static-files:/RackHD/files

  rackhd:
    image: uksuv/infra-simmer-rackhd:${INFRASIMMER_RACKHD_TAG:-latest}
    privileged: true
    ports: ["8080:8080", "8443:8443"]
    volumes:
      - monorail-static-files:/RackHD/on-tftp/static/tftp:ro
      - monorail-static-files:/RackHD/on-http/static/http:ro
    networks:
      zonctrol:
        ipv4_address: 172.31.128.2
      default:
    depends_on:
      - files
      - mongo
      - rabbitmq
