#!/usr/bin/env bash

git clone --recursive https://github.com/RackHD/RackHD
pushd RackHD
git checkout ${RACKHD_TAG:-master}
git clone https://github.com/RackHD/ucs-service
pushd ucs-service
git checkout ${RACKHD_TAG:-master}
popd
popd

# turn the packer/ansible config.json into one we can use.
python3 xform_scripts/make_monorail_conf_files

# Other helper files we will want in the rackhd-blob
cp drop_in_files/* RackHD

docker build RackHD -t uksuv/infra-simmer-rackhd:${RACKHD_BLOB_VERSION:-latest}
